# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: 0.6
    - julia: nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("PolynomialFactors"); Pkg.test("PolynomialFactors"; coverage=true)'
# uncomment the following lines to get coverage information
#after_success:
#    - julia -e 'cd(Pkg.dir("PolynomialFactors")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())';
